### ISSUE TITLE
犯不上那么敏感

### ISSUE THREAD

**Issue by Grass-block** [hehe1005566889/hehe1005566889#1]
犯不上那么敏感，搞得谁都不开心
我也没空看你那堆项目，反正都一刀两断了
我取消关注就好
删了这个issue代表你看完了

**Comment by hehe1005566889** [comment]
滚，谁说你了，我号发生什么了凭啥跟你说

**Comment by Grass-block** [comment]
都知道你说的是谁，没必要

哦对了，我干的这堆sb事情其实不是我一个人的旨意
我背后其实一直还有一个人
不过我（们）已经达到目的了
