### ISSUE TITLE
别老自作多情谢谢

### ISSUE THREAD

**Issue by Grass-block** [hehe1005566889/hehe1005566889#2]
第一 nobody asks
第二 没人看你那仓库
第三 我早就unfollow了
好话之前给你说了

**Comment by hehe1005566889** [comment]
滚，去死，谁tmd说你了傻逼
谁先自作多情的

**Comment by hehe1005566889** [comment]
从何而得来的，介绍上说的你傻逼

**Comment by hehe1005566889** [comment]
谁tmd说你了，自己给自己贴标签，还来别人这里开issue喷，这种行为谁是傻逼我不说
